name: Test and coverage
on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: llvm-tools-preview

      - name: Setup just
        uses: extractions/setup-just@v1

      - uses: Swatinem/rust-cache@v1

      - name: Coverage
        run: just cov

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
